import pyautogui as py
py.press("win")
py.write("chrome")
py.press("enter")
py.sleep(2)
py.write("senai.americana")
py.press("enter")
py.sleep(2)
py.click(151,533,button="left")
py.sleep(3)
py.click(1087,856,button="left")
py.sleep(2)
print(py.position())
py.click(66,1079,button="left")
py.sleep(1)
py.write("python")
py.sleep(1)
py.press("enter")
py.vscroll(-500)

